- CHANGELOG.md
- pom.xml
> :bookmark: version 4.1.0

- src/main/java/com/mindee/http/MindeeApi.java
- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/http/MindeeHttpException.java
- src/test/java/com/mindee/http/MindeeHttpApiTest.java
Make all server errors be of type `MindeeHttpException`.
Always provide the HTTP code in the error message.
If the server response can't be parsed properly, provide this information in the error details.
New unit tests
> Better errors

- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/extraction/ImageExtractor.java
- src/main/java/com/mindee/input/LocalInputSource.java
- src/test/java/com/mindee/extraction/ImageExtractorTest.java
Add the ability to extract sub-images from individual pages.
Auto-detect if the source image is a PDF when constructing the image extractor.
If it's a PDF, extract each PDF page to an individual image.
> :sparkles: add ability to extract sub-images from PDFs

- src/main/java/com/mindee/pdf/PDFUtils.java
Avoid a warning when the PDF file is not closed after extracting images.
Lower DPI on extracted images for bandwidth and processing considerations.
> :bug: fix for not closing the PDF document

- README.md
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/input/LocalResponse.java
- src/main/java/com/mindee/input/WebhookSource.java
- src/test/java/com/mindee/MindeeClientTest.java
Implement a way to load JSON data from a webhook.
> :sparkles: add ability to easily load a webhook response

- .gitignore
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
* add support for invoice v4.6
* add support for findoc 1.6
> :sparkles: update invoice to 4.6, financial document to 1.6

- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/receipt/ReceiptV5.java
- src/main/java/com/mindee/product/receipt/ReceiptV5Document.java
- src/test/java/com/mindee/product/receipt/ReceiptV5Test.java
* :sparkles: update receipt API to v5.2
* :sparkles: update financial doc API to 1.7
* :recycle: update test lib
> :sparkles: update financial document to 1.7 & receipt to 5.2

- src/main/java/com/mindee/geometry/Bbox.java
- src/main/java/com/mindee/geometry/Point.java
- src/main/java/com/mindee/geometry/Polygon.java
- src/main/java/com/mindee/parsing/custom/lineitems/LineGenerator.java
- src/test/java/com/mindee/geometry/BboxUtilsTest.java
Add the ability to convert `Bbox` to and from `Polygon` objects.
> :sparkles: allow converting between bboxes and polygons

- src/main/java/com/mindee/parsing/custom/lineitems/LineGenerator.java
- src/main/java/com/mindee/parsing/custom/lineitems/LineItemsGenerator.java
- src/main/java/com/mindee/parsing/custom/lineitems/PreparedLines.java
- src/test/java/com/mindee/parsing/custom/lineitems/FakeListField.java
- src/test/java/com/mindee/parsing/custom/lineitems/LineGeneratorTest.java
Allow passing multiple anchors for line reconstruction. Choose the one with the most lines.
> :sparkles: allow sending multiple anchors when building line items

- docs/delivery_notes_v1.md
- src/main/java/com/mindee/product/deliverynote/DeliveryNoteV1Document.java
> :sparkles: update delivery note 1.1

- CHANGELOG.md
- README.md
- docs/custom_v1.md
- docs/getting_started.md
- pom.xml
> :bookmark: Version 4.23.0

- docs/code_samples/us_mail_v3_async.txt
- docs/us_mail_v3.md
- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/parsing/SummaryHelper.java
- src/main/java/com/mindee/parsing/standard/BooleanField.java
- src/main/java/com/mindee/parsing/standard/StringField.java
- src/main/java/com/mindee/product/us/usmail/UsMailV3.java
- src/main/java/com/mindee/product/us/usmail/UsMailV3Document.java
- src/main/java/com/mindee/product/us/usmail/UsMailV3RecipientAddress.java
- src/main/java/com/mindee/product/us/usmail/UsMailV3SenderAddress.java
- src/test/java/com/mindee/product/us/usmail/UsMailV3Test.java
> :sparkles: add support for us mail v3

- src/main/java/com/mindee/parsing/generated/GeneratedFeature.java
- src/main/java/com/mindee/parsing/generated/GeneratedObject.java
- src/test/java/com/mindee/product/generated/GeneratedV1Test.java
> :bug: fix missing boolean field accessor for generated objects

- docs/code_samples/invoice_splitter_v1_async.txt
- docs/financial_document_v1.md
- docs/invoice_splitter_v1.md
- docs/invoices_v4.md
- src/main/java/com/mindee/extraction/PDFExtractor.java
- src/main/java/com/mindee/product/ind/indianpassport/IndianPassportV1Document.java
- src/main/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1.java
- src/main/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1Document.java
- src/main/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1InvoicePageGroup.java
- src/test/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1Test.java
> :recycle: update display & structure for invoice splitter v1

- docs/expense_receipts_v5.md
- docs/financial_document_v1.md
- docs/idcard_fr_v2.md
- docs/ind_passport_v1.md
- docs/international_id_v2.md
- docs/invoice_splitter_v1.md
- docs/invoices_v4.md
- docs/resume_v1.md
- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/cli/CommandLineInterfaceProducts.java
- src/main/java/com/mindee/cli/ProductProcessor.java
- src/main/java/com/mindee/product/deliverynote/DeliveryNoteV1Document.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1LineItem.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4LineItem.java
- src/main/java/com/mindee/product/receipt/ReceiptV5Document.java
- src/main/java/com/mindee/product/receipt/ReceiptV5LineItem.java
> :recycle: update CLI syntax & files layout

- src/main/java/com/mindee/CommandLineInterface.java
- src/test/java/com/mindee/http/MindeeHttpApiTest.java
Fix for
```
Running com.mindee.http.MindeeHttpApiTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE!
warning(junit.framework.TestSuite$1)  Time elapsed: 0.003 sec  <<< FAILURE!
junit.framework.AssertionFailedError: No tests found in com.mindee.http.MindeeHttpApiTest
```
> :bug: fix for no tests found

- src/main/java/com/mindee/CommandLineInterface.java
> :sparkles: add OCR output to CLI

- docs/financial_document_v1.md
- docs/invoices_v4.md
- docs/us_healthcare_cards_v1.md
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/main/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Copay.java
- src/main/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Document.java
- src/test/java/com/mindee/product/financialdocument/FinancialDocumentV1Test.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
- src/test/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Test.java
> :sparkles: add support for Findoc V1.12, Invoices V4.10, US Healthcare Cards V1.2

- README.md
- docs/code_samples/workflow_execution.txt
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/PredictOptions.java
- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/parsing/common/Rag.java
- src/test/java/com/mindee/workflow/WorkflowIT.java
> :sparkles: add support for workflow polling

- docs/energy_bill_fra_v1.md
- docs/expense_receipts_v5.md
- docs/financial_document_v1.md
- docs/ind_passport_v1.md
- docs/invoices_v4.md
- docs/us_healthcare_cards_v1.md
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/ind/indianpassport/IndianPassportV1Document.java
- src/main/java/com/mindee/product/internationalid/InternationalIdV2Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/main/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1Document.java
- src/main/java/com/mindee/product/receipt/ReceiptV5Document.java
- src/main/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Copay.java
- src/main/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Document.java
- src/test/java/com/mindee/product/ind/indianpassport/IndianPassportV1Test.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
- src/test/java/com/mindee/product/us/healthcarecard/HealthcareCardV1Test.java
> :sparkles: add support for financial document v1.14, US healthcare cards v1.3 & invoice v4.11

- pom.xml
- src/main/java/com/mindee/extraction/PDFExtractor.java
- src/main/java/com/mindee/input/InputSourceUtils.java
- src/main/java/com/mindee/pdf/PDFUtils.java
- src/main/java/com/mindee/pdf/PdfBoxApi.java
- src/main/java/com/mindee/pdf/PdfCompressor.java
- src/test/java/com/mindee/input/LocalInputSourceTest.java
- src/test/java/com/mindee/pdf/PDFUtilsTest.java
Bump pdfbox from 2.0.31 to 3.0.5 and fix breaking changes
> :arrow_up: Bump pdfbox from 2.0.31 to 3.0.5

- .github/workflows/_publish-code.yml
- .gitignore
- pom.xml
> :recycle: migrate to maven central

- docs/code_samples/default_v2.txt
- src/main/java/com/mindee/input/LocalInputSource.java
- src/test/java/com/mindee/MindeeClientV2IT.java
> :recycle: harmonize names with other libs

- src/main/java/com/mindee/parsing/v2/field/BaseField.java
- src/main/java/com/mindee/parsing/v2/field/DynamicFieldDeserializer.java
- src/main/java/com/mindee/parsing/v2/field/ListField.java
- src/main/java/com/mindee/parsing/v2/field/ObjectField.java
- src/main/java/com/mindee/parsing/v2/field/SimpleField.java
- src/main/java/com/mindee/parsing/v2/field/SimpleFieldDeserializer.java
- src/test/java/com/mindee/parsing/v2/InferenceTest.java
Fix confidence and locations not being deserialized.
> :bug: fix for locations and confidence

- src/main/java/com/mindee/input/PageOptions.java
- src/test/java/com/mindee/pdf/PdfOperationTest.java
Fix documentation of page options
> :memo: fix documentation of page options
