- pom.xml
Use of profiles for maven deploy
optimizing deployment
configuration changes - tested manually by deploying to maven
> use of profiles

- pom.xml
> version update

- .github/workflows/maven-publish.yml
- CHANGELOG.md
- README.md
- pom.xml
> :arrow_up: fix for Uncontrolled Resource Consumption in Jackson-databind

- cli.sh
- src/main/java/com/mindee/CLI.java
Fixes so that the CLI tool works with the latest version.
> :bug: fixes and updates for CLI tool

- .github/workflows/maven-publish.yml
:construction_worker: fixes to automated publishing
Tested by verifying results on sonatype.org
> :construction_worker: fixes to automated publishing

- .editorconfig
- .github/workflows/codeql.yml
- CHANGELOG.md
- README.md
- src/main/java/com/mindee/CLI.java
- src/main/java/com/mindee/documentparser/DocumentConfigFactory.java
- src/main/java/com/mindee/model/deserialization/DocumentResponseDeserializerFactory.java
- src/main/java/com/mindee/model/documenttype/invoice/InvoiceLineItem.java
- src/main/java/com/mindee/model/documenttype/invoice/InvoiceV4Response.java
- src/test/java/com/mindee/model/deserialization/DocumentResponseDeserializerTest.java
> ✨ Add Invoice v4

- pom.xml
- src/main/java/com/mindee/model/documenttype/invoice/InvoiceLineItem.java
- src/main/java/com/mindee/model/documenttype/invoice/InvoiceV4Response.java
- src/test/java/com/mindee/model/deserialization/DocumentResponseDeserializerTest.java
Invoice v4 not fully implemented
> 🐛 Invoice v4 not fully implemented

- pom.xml
> :arrow_up: update httpClient and picocli

- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/DocumentToParse.java
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/PageOptions.java
* Add `--output-type` option to CLI
* rework and simplify the CLI classes
> :recycle: :bug: rework CLI, fix minor bugs along the way

- .github/workflows/docs.yml
- .github/workflows/test-code-samples.yml
- checkstyle.xml
- tests/test_code_samples.sh
Publish javadocs and code samples.
> :memo: publish javadocs and code samples

- docs/code_samples/bank_account_details_v1.txt
- docs/code_samples/bank_check_v1.txt
- docs/code_samples/base.jsh
- docs/code_samples/carte_vitale_v1.txt
- docs/code_samples/custom_v1.txt
- docs/code_samples/default.txt
- docs/code_samples/expense_receipts_v4.txt
- docs/code_samples/financial_document_v1.txt
- docs/code_samples/idcard_fr_v1.txt
- docs/code_samples/invoices_v4.txt
- docs/code_samples/license_plates_v1.txt
- docs/code_samples/passport_v1.txt
- docs/code_samples/proof_of_address_v1.txt
- docs/code_samples/shipping_container_v1.txt
- src/main/java/com/mindee/parsing/fr/bankaccountdetails/BankAccountDetailsV1DocumentPrediction.java
- src/main/java/com/mindee/parsing/fr/bankaccountdetails/BankAccountDetailsV1Inference.java
- src/test/java/com/mindee/parsing/fr/bankaccountdetails/BankAccountDetailsV1Test.java
* :sparkles: add support for FR bank account details
* :memo: make code samples easier to read
Auto-generated code!
> Add fr bank account

- docs/code_samples/bank_account_details_v2.txt
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Bban.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Document.java
- src/test/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Test.java
:robot: add support for FR bank account details v2
> :sparkles: add support for FR bank account details v2

- src/main/java/com/mindee/parsing/SummaryHelper.java
- src/main/java/com/mindee/parsing/standard/PositionField.java
- src/main/java/com/mindee/product/eu/licenseplate/LicensePlateV1.java
- src/main/java/com/mindee/product/eu/licenseplate/LicensePlateV1Document.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1LineItem.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1Document.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Bban.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Document.java
- src/main/java/com/mindee/product/fr/cartevitale/CarteVitaleV1.java
- src/main/java/com/mindee/product/fr/cartevitale/CarteVitaleV1Document.java
- src/main/java/com/mindee/product/fr/idcard/IdCardV1.java
- src/main/java/com/mindee/product/fr/idcard/IdCardV1Document.java
- src/main/java/com/mindee/product/fr/idcard/IdCardV1Page.java
- src/main/java/com/mindee/product/passport/PassportV1.java
- src/main/java/com/mindee/product/passport/PassportV1Document.java
- src/main/java/com/mindee/product/proofofaddress/ProofOfAddressV1.java
- src/main/java/com/mindee/product/proofofaddress/ProofOfAddressV1Document.java
- src/main/java/com/mindee/product/receipt/ReceiptV5.java
- src/main/java/com/mindee/product/receipt/ReceiptV5Document.java
- src/main/java/com/mindee/product/receipt/ReceiptV5LineItem.java
- src/main/java/com/mindee/product/us/bankcheck/BankCheckV1.java
- src/main/java/com/mindee/product/us/bankcheck/BankCheckV1Document.java
- src/main/java/com/mindee/product/us/bankcheck/BankCheckV1Page.java
- src/test/java/com/mindee/product/us/bankcheck/BankCheckV1Test.java
* :bug: fix for missing page data in us bank check
* :bug: fix passport to match API return
* regenerate all product files.
> :bug: fix for missing page data in us bank check

- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
- src/test/java/com/mindee/product/receipt/ReceiptV4Test.java
:white_check_mark: add unit tests for receipt v4, invoice v4
> :white_check_mark: add unit tests for receipt v4, invoice v4

- src/test/java/com/mindee/MindeeClientTest.java
- src/test/java/com/mindee/http/MindeeHttpApiTest.java
- src/test/java/com/mindee/input/LocalInputSourceTest.java
- src/test/java/com/mindee/parsing/common/OcrTest.java
- src/test/java/com/mindee/product/custom/CustomV1Test.java
- src/test/java/com/mindee/product/custom/CustomV1WithLineItemsTest.java
- src/test/java/com/mindee/product/eu/licenseplate/LicensePlateV1Test.java
- src/test/java/com/mindee/product/financialdocument/FinancialDocumentV1Test.java
- src/test/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1Test.java
- src/test/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Test.java
- src/test/java/com/mindee/product/fr/cartevitale/CarteVitaleV1Test.java
- src/test/java/com/mindee/product/fr/idcard/IdCardV1Test.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
- src/test/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1Test.java
- src/test/java/com/mindee/product/passport/PassportV1Test.java
- src/test/java/com/mindee/product/proofofaddress/ProofOfAddressV1Test.java
- src/test/java/com/mindee/product/receipt/ReceiptV4Test.java
- src/test/java/com/mindee/product/receipt/ReceiptV5Test.java
- src/test/java/com/mindee/product/us/bankcheck/BankCheckV1Test.java
- src/test/java/com/mindee/product/us/driverlicense/DriverLicenseV1Test.java
- tests/test_code_samples.sh
> :arrow_up: update to new test resources structure

- docs/java-getting-started.md
- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/PredictOptions.java
- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/http/RequestParameters.java
- src/main/java/com/mindee/parsing/common/Cropper.java
- src/main/java/com/mindee/parsing/common/Inference.java
- src/main/java/com/mindee/parsing/common/Page.java
- src/main/java/com/mindee/parsing/common/ocr/Word.java
- src/test/java/com/mindee/MindeeClientTest.java
- src/test/java/com/mindee/http/MindeeHttpApiTest.java
- src/test/java/com/mindee/parsing/common/CropperTest.java
- src/test/java/com/mindee/parsing/common/OcrTest.java
Add the cropper option to the extras. This requires reworking the undocumented `allWords` parameter.
> :sparkles: add cropper option

- docs/code_samples/us_w9_v1.txt
- src/main/java/com/mindee/geometry/Polygon.java
- src/main/java/com/mindee/parsing/standard/BaseField.java
- src/main/java/com/mindee/parsing/standard/PositionField.java
- src/main/java/com/mindee/product/us/w9/W9V1.java
- src/main/java/com/mindee/product/us/w9/W9V1Document.java
- src/main/java/com/mindee/product/us/w9/W9V1Page.java
- src/test/java/com/mindee/product/us/w9/W9V1Test.java
* auto-generated product files
* changes to PositionField printing
> :sparkles: add support for US w9 v1

- docs/code_samples/barcode_reader_v1.txt
- src/main/java/com/mindee/product/barcodereader/BarcodeReaderV1.java
- src/main/java/com/mindee/product/barcodereader/BarcodeReaderV1Document.java
- src/main/java/com/mindee/product/barcodereader/BarcodeReaderV1Page.java
- src/test/java/com/mindee/product/barcodereader/BarcodeReaderV1Test.java
> :sparkles: add barcode reader v1

- docs/code_samples/idcard_fr_v2.txt
- src/main/java/com/mindee/product/fr/idcard/IdCardV2.java
- src/main/java/com/mindee/product/fr/idcard/IdCardV2Document.java
- src/main/java/com/mindee/product/fr/idcard/IdCardV2Page.java
- src/test/java/com/mindee/product/fr/idcard/IdCardV2Test.java
> :sparkles: add support for FR ID card v2

- src/test/java/com/mindee/product/cropper/CropperV1Test.java
- src/test/java/com/mindee/product/eu/licenseplate/LicensePlateV1Test.java
- src/test/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1Test.java
- src/test/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Test.java
- src/test/java/com/mindee/product/fr/cartevitale/CarteVitaleV1Test.java
- src/test/java/com/mindee/product/fr/idcard/IdCardV1Test.java
- src/test/java/com/mindee/product/fr/idcard/IdCardV2Test.java
- src/test/java/com/mindee/product/passport/PassportV1Test.java
- src/test/java/com/mindee/product/proofofaddress/ProofOfAddressV1Test.java
- src/test/java/com/mindee/product/receipt/ReceiptV5Test.java
- src/test/java/com/mindee/product/us/bankcheck/BankCheckV1Test.java
- src/test/java/com/mindee/product/us/driverlicense/DriverLicenseV1Test.java
- src/test/java/com/mindee/product/us/w9/W9V1Test.java
Update unit tests to check all empty properties. Auto-generated.
> :white_check_mark: update tests to check all product properties

- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/parsing/common/ApiResponse.java
- src/test/java/com/mindee/http/MindeeHttpApiTest.java
Add the raw string response from the server to all Response objects.
> :sparkles: add raw response string in response object

- checkstyle.xml
- docs/code_samples/invoice_splitter_v1_async.txt
- src/main/java/com/mindee/AsyncPollingOptions.java
- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/input/InputSourceUtils.java
- src/main/java/com/mindee/input/PageOptions.java
- src/main/java/com/mindee/parsing/common/AsyncPredictResponse.java
Add automated polling for async requests.
> :sparkles: add built-in async call polling

- docs/code_samples/multi_receipts_detector_v1.txt
- src/main/java/com/mindee/geometry/Polygon.java
- src/main/java/com/mindee/http/MindeeHttpException.java
- src/main/java/com/mindee/parsing/standard/PositionField.java
- src/main/java/com/mindee/product/multireceiptsdetector/MultiReceiptsDetectorV1.java
- src/main/java/com/mindee/product/multireceiptsdetector/MultiReceiptsDetectorV1Document.java
- src/test/java/com/mindee/product/multireceiptsdetector/MultiReceiptsDetectorV1Test.java
Add multi receipts detector v1, auto-generated
> :sparkles: add multi receipts detector v1

- .github/workflows/test-code-samples.yml
- CHANGELOG.md
- pom.xml
- src/main/java/com/mindee/product/us/w9/W9V1.java
- src/main/java/com/mindee/product/us/w9/W9V1Document.java
- src/main/java/com/mindee/product/us/w9/W9V1Page.java
> :bookmark: version 4.4.0

- docs/code_samples/invoice_splitter_v1_async.txt
- src/main/java/com/mindee/parsing/common/AsyncPredictResponse.java
- src/test/java/com/mindee/product/invoicesplitter/InvoiceSplitterV1Test.java
Fixes and tweaks to asynchronous code sample.
> ✨ add a method to simplify getting the document object

- src/main/java/com/mindee/parsing/SummaryHelper.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1Document.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1LineItem.java
- src/main/java/com/mindee/product/invoice/InvoiceV4.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4LineItem.java
- src/main/java/com/mindee/product/receipt/ReceiptV5LineItem.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
- src/test/java/com/mindee/product/us/w9/W9V1Test.java
autogenerated update of products
> :arrow_up: update test files

- src/main/java/com/mindee/parsing/common/Document.java
- src/test/java/com/mindee/parsing/common/AsyncPredictResponseTest.java
Add `n_pages` property as `nPages` to `Document` class.
> :sparkles: add nPages to Document class

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.5.0

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.5.1

- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/MindeeClient.java
* :sparkles: add raw output to CLI
* :recycle: minor cleanup
> :sparkles: add raw output to CLI

- src/main/java/com/mindee/extraction/ExtractedImage.java
- src/main/java/com/mindee/extraction/ImageExtractor.java
- src/main/java/com/mindee/geometry/BboxUtils.java
- src/main/java/com/mindee/geometry/Polygon.java
- src/main/java/com/mindee/geometry/PolygonUtils.java
- src/main/java/com/mindee/input/InputSourceUtils.java
- src/main/java/com/mindee/input/LocalInputSource.java
- src/main/java/com/mindee/parsing/custom/lineitems/LineItemsGenerator.java
- src/main/java/com/mindee/parsing/standard/BaseField.java
- src/main/java/com/mindee/parsing/standard/PositionData.java
- src/main/java/com/mindee/parsing/standard/PositionField.java
- src/main/java/com/mindee/pdf/PDFUtils.java
- src/test/java/com/mindee/extraction/ImageExtractorTest.java
- src/test/java/com/mindee/parsing/common/AsyncPredictResponseTest.java
- src/test/java/com/mindee/parsing/common/ErrorTest.java
- src/test/java/com/mindee/pdf/PDFUtilsTest.java
- src/test/java/com/mindee/pdf/PdfOperationTest.java
Add ability to extract images from cropping data.
> add extracted image

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.9.0

- src/main/java/com/mindee/parsing/standard/StringField.java
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
* Update to invoice v1.4
* :boom: the method `getTotalTaxes()`  was replaced by `getTotalTax()` following implementation of this in the API.
> :arrow_up: update invoice to 4.4

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.10.0

- src/main/java/com/mindee/http/MindeeHttpApi.java
- src/main/java/com/mindee/parsing/common/ApiRequest.java
- src/main/java/com/mindee/parsing/common/Cropper.java
- src/main/java/com/mindee/parsing/common/Error.java
- src/main/java/com/mindee/parsing/common/Extras.java
- src/main/java/com/mindee/parsing/common/Job.java
- src/test/java/com/mindee/MindeeClientTest.java
- src/test/java/com/mindee/parsing/common/AsyncPredictResponseTest.java
Code update following server update.
> :sparkles: handle job errors separately from API errors

- docs/code_samples/invoices_v4.txt
- src/main/java/com/mindee/product/invoice/InvoiceV4Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4LineItem.java
- src/test/java/com/mindee/product/invoice/InvoiceV4Test.java
:sparkles: update Invoice to v4.5
> :sparkles: update Invoice to v4.5

- .github/workflows/docs.yml
- .github/workflows/maven-publish.yml
- src/main/java/com/mindee/parsing/generated/GeneratedFeature.java
> :bug: fix docs

- .github/workflows/build.yml
- .github/workflows/checkstyle.yml
- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/maven-publish.yml
- .github/workflows/test-code-samples.yml
- pom.xml
> :white_check_mark: add testing for Java 21

- src/main/java/com/mindee/CommandLineInterface.java
- src/main/java/com/mindee/input/LocalResponse.java
- src/test/java/com/mindee/input/LocalInputSourceTest.java
- src/test/java/com/mindee/input/LocalResponseTest.java
> :sparkles: add HMAC validation for webhooks

- src/main/java/com/mindee/parsing/generated/GeneratedObject.java
- src/test/java/com/mindee/product/generated/GeneratedV1Test.java
Some minor improvements when accessing Generated properties.
> :art: a few minor improvements to using Generated products

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.14.0

- src/main/java/com/mindee/parsing/SummaryHelper.java
- src/main/java/com/mindee/parsing/standard/BooleanField.java
> :sparkles: add boolean field support

- src/main/java/com/mindee/geometry/Bbox.java
- src/test/java/com/mindee/parsing/custom/lineitems/LineGeneratorTest.java
Remove redundant ArrayList constructor.
> :art: simplify array init

- src/main/java/com/mindee/parsing/standard/AmountField.java
- src/main/java/com/mindee/parsing/standard/BaseField.java
- src/main/java/com/mindee/parsing/standard/BooleanField.java
- src/main/java/com/mindee/parsing/standard/ClassificationField.java
- src/main/java/com/mindee/parsing/standard/CompanyRegistrationField.java
- src/main/java/com/mindee/parsing/standard/DateField.java
- src/main/java/com/mindee/parsing/standard/LocaleField.java
- src/main/java/com/mindee/parsing/standard/PaymentDetailsField.java
- src/main/java/com/mindee/parsing/standard/StringField.java
- src/main/java/com/mindee/parsing/standard/TaxField.java
- src/main/java/com/mindee/product/financialdocument/FinancialDocumentV1LineItem.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV1Document.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Bban.java
- src/main/java/com/mindee/product/fr/bankaccountdetails/BankAccountDetailsV2Document.java
- src/main/java/com/mindee/product/invoice/InvoiceV4LineItem.java
- src/main/java/com/mindee/product/receipt/ReceiptV5LineItem.java
- src/main/java/com/mindee/product/resume/ResumeV1.java
- src/main/java/com/mindee/product/resume/ResumeV1Certificate.java
- src/main/java/com/mindee/product/resume/ResumeV1Document.java
- src/main/java/com/mindee/product/resume/ResumeV1Education.java
- src/main/java/com/mindee/product/resume/ResumeV1Language.java
- src/main/java/com/mindee/product/resume/ResumeV1ProfessionalExperience.java
- src/main/java/com/mindee/product/resume/ResumeV1SocialNetworksUrl.java
Utility method to shorten code.
> :sparkles: add isEmpty() method to field classes

- src/main/java/com/mindee/parsing/standard/CompanyRegistrationField.java
- src/main/java/com/mindee/parsing/standard/LocaleField.java
- src/main/java/com/mindee/parsing/standard/PaymentDetailsField.java
Make it easier to init feature objects.
> :recycle: add public construcors to more feature classes

- src/main/java/com/mindee/parsing/standard/TaxField.java
Make it possible to construct a TaxField from other data.
> :recycle: add a public constructor for the TaxField class

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.17.0

- pom.xml
> :arrow_up: updates to various dependencies

- src/main/java/com/mindee/parsing/standard/CompanyRegistrationField.java
Print out the type of registration for a better world.
> :recycle: print out the registration type

- .github/workflows/integration-tests.yml
- .gitignore
- .gitmodules
- pom.xml
- src/main/java/com/mindee/extraction/ExtractedPDF.java
- src/main/java/com/mindee/extraction/PDFExtractor.java
- src/main/java/com/mindee/pdf/PDFUtils.java
- src/test/java/com/mindee/TestingUtilities.java
- src/test/java/com/mindee/extraction/InvoiceSplitterAutoExtractionIT.java
- src/test/java/com/mindee/extraction/PDFExtractorTest.java
* :sparkles: add support for invoice splitter auto-extraction
* :arrow_up: add support for integration tests
* :recycle: refactor some pdf processing code
* :recycle: cleanup pom.xml versions
* :arrow_up: bump okhttp3 to 4.12
> :sparkles: add support for invoice splitter auto-extraction

- .github/workflows/integration-tests.yml
* :recycle: fix broken GH action for integration tests
> :recycle: fix workflow run for integration tests

- docs/code_samples/invoices_v4_async.txt
What it says on the name of the pr
> :recycle: add async invoice call

- src/main/java/com/mindee/PredictOptions.java
> :memo: fix doc string that broke the entire Doc CI

- CHANGELOG.md
- pom.xml
> :bookmark: version 4.18.0

- README.md
- docs/idcard_fr_v2.md
> :memo: update README & idcard_fr_v2 slug

- README.md
- docs/invoice_splitter_v1.md
> :memo: fix broken documentation URLs

- docs/custom_v1.md
> :memo: fix broken documentation URLs, part 2

- .github/workflows/test-code-samples.yml
> :wrench: update checkout@v3 to checkout@v4 on all actions

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.19.0

- .github/workflows/docs.yml
fix doc workflow not ublishing
> :wrench: fix doc workflow

- example/AutoInvoiceSplitterExtractionExample.java
- example/AutoMultiReceiptExtractionExample.java
- src/test/java/com/mindee/TestingUtilities.java
- src/test/java/com/mindee/extraction/InvoiceSplitterAutoExtractionIT.java
* :recycle: update invoicesplitter integration test to rely on levenshtein distance ratio
* :recycle: add example files for invocie splitter auto-extraction & multi-receipts auto-extraction
> :recycle: update integration tests, add examples for latest features

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.20.0

- src/main/java/com/mindee/parsing/common/InferenceExtras.java
- src/main/java/com/mindee/parsing/common/Job.java
- src/main/java/com/mindee/parsing/common/LocalDateTameTimeDeserializer.java
:recycle: add explicit jackson deserializers to match existing syntax + extract date deserializer from Job
> :recycle: add deserializer + extract custom deserializing date class

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.22.0

- src/main/java/com/mindee/MindeeClient.java
- src/main/java/com/mindee/extraction/ExtractedImage.java
- src/main/java/com/mindee/extraction/ExtractedPDF.java
- src/main/java/com/mindee/extraction/ImageExtractor.java
- src/main/java/com/mindee/extraction/PDFExtractor.java
> :memo: cleanup javadoc & add missing entries

- .github/workflows/docs.yml
- pom.xml
> :memo: fix documentation

- src/main/java/com/mindee/parsing/generated/GeneratedObject.java
- src/test/java/com/mindee/product/generated/GeneratedV1Test.java
.asAmountField() causes class java.lang.Integer cannot be cast to class java.lang.Double
> :bug: fix for server not properly formatting floats

- src/main/java/com/mindee/AsyncPollingOptions.java
- src/main/java/com/mindee/MindeeClient.java
> :bug: fix for large files timing out in async mode

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.24.2

- src/main/java/com/mindee/AsyncPollingOptions.java
> :recycle: increase async retry timers

- .github/workflows/_publish-guide.yml
- src/main/java/com/mindee/http/MindeeApi.java
> :bug: harmonize OS names across clients

- src/main/java/com/mindee/CommandLineInterface.java
> :bug: fix product description missing in CLI help

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.27.0

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.28.0

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.29.0

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.31.0

- docs/financial_document_v1.md
- docs/invoices_v4.md
- docs/us_mail_v3.md
> :memo: fix typos in md documentation

- CHANGELOG.md
- pom.xml
> :bookmark: Version 4.32.0

- .github/workflows/_publish-code.yml
> :bug: fix deploy to central

- CHANGELOG.md
- pom.xml
- src/test/java/com/mindee/parsing/v2/InferenceTest.java
> :bookmark: Version 4.33.0-rc1

- src/test/java/com/mindee/parsing/v2/InferenceTest.java
tests for https://docs.mindee.com/getting-started/integrating-mindee#tab-java-1
> :white_check_mark: add unit tests related to the documentation
